language: cpp
compiler: gcc
sudo: true

install:
  - sudo ./install_packages.sh
  - sudo ./install_lib_nds.sh

script:
  # Do not call qmake, this will not work
  - make
  #- ./travis_qmake_gcc_cpp98_libnds
  #- desmume CppHelloWorldQtCreatorUbuntuNds.nds