# From https://devkitpro.org/wiki/Getting_Started/devkitARM
language: cpp
compiler: gcc

install:
  - my_github=${PWD##*/} 
  - echo $my_github
  # Create folder structure
  - sudo mkdir -p /opt/devkitpro
  - sudo chmod 777 /opt/devkitpro
  # Go to that folder
  - cd /opt/devkitpro
  # Download and extract devkitARM
  - sudo wget https://sourceforge.net/projects/devkitpro/files/devkitARM/devkitARM_r47/devkitARM_r47-x86_64-linux.tar.bz2
  # Extract
  - sudo tar -xvjf devkitARM_r47-x86_64-linux.tar.bz2
  # libnds
  - mkdir libnds
  - cd libnds
  - sudo wget https://sourceforge.net/projects/devkitpro/files/libnds/1.7.1/libnds-1.7.1.tar.bz2
  - sudo tar -xvjf libnds-1.7.1.tar.bz2
  # libfat (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/libfat/1.1.2/libfat-nds-1.1.2.tar.bz2
  - sudo tar -xvjf libfat-nds-1.1.2.tar.bz2
  # dswifi (subfolder of libnds)
  - sudo wget https://sourceforge.net/projects/devkitpro/files/dswifi/0.4.0/dswifi-0.4.0.tar.bz2
  - sudo tar -xvjf dswifi-0.4.0.tar.bz2

script:
  # Do not call qmake, this will not work
  - cd $my_github
  - make
  #- ./travis_qmake_gcc_cpp98_libnds
  #- desmume CppHelloWorldQtCreatorUbuntuNds.nds